THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[50, 50, 50]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[50, 50, 50]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 32, 256]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 32, 256]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 1024, 1024]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 1024, 1024]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 4096, 16384]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 4096, 16384]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 35, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(K, N).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25

 - - - - 

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[50, 50, 50]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[50, 50, 50]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 32, 256]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 32, 256]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 1024, 1024]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 1024, 1024]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 4096, 16384]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[128, 4096, 16384]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 69, in main
    A, B = torch.randn(M, K).cuda(), torch.randn(N, K).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25

 - - - - 

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26, 250]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26, 250]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26, 500]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26, 500]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26, 1024]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[72, 26, 26, 1024]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[50, 50, 50, 500]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[50, 50, 50, 500]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[50, 50, 50, 1024]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[50, 50, 50, 1024]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 77, in main
    A, B = torch.randn(B, N, M).cuda(), torch.randn(B, K, M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25

 - - - - 

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[32, 16, 16, 14, 14]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[32, 16, 16, 14, 14]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[32, 32, 32, 7, 7]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[32, 32, 32, 7, 7]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[32, 4, 4, 56, 56]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[32, 4, 4, 56, 56]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[32, 8, 8, 28, 28]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[32, 8, 8, 28, 28]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[256, 256, 512, 14, 3]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[256, 256, 512, 14, 3]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 60, in main
    IN = torch.randn(batch, in_channel, in_size, in_size).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25

 - - - - 

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[1000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[1000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[10000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[10000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[100000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[100000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[1000000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[1000000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[10000000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
[10000000]
Traceback (most recent call last):
  File "tc/tc_bench.py", line 82, in <module>
    main()
  File "tc/tc_bench.py", line 43, in main
    A = torch.randn(M).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25

 - - - - 

